(define (problem caso3-ext2-estancia-exacta-optimizada)
  (:domain viaje-extension2)

  (:objects
    barcelona paris roma berlin lisboa oporto viena praga - city
    hbarcelona hparis hroma hberlin hlisboa hoporto hviena hpraga - hotel
  )

  (:init
    (= (visited-count) 0)
    (= (min-cities) 5)
    (= (min-days-city) 2)
    (= (max-days-city) 2)
    (= (total-days) 0)
    (= (min-total-days) 10)
    (= (total-interest) 0)

    (= (days-in-city barcelona) 0)
    (= (days-in-city paris) 0)
    (= (days-in-city roma) 0)
    (= (days-in-city berlin) 0)
    (= (days-in-city lisboa) 0)
    (= (days-in-city oporto) 0)
    (= (days-in-city viena) 0)
    (= (days-in-city praga) 0)

    (= (city-interest barcelona) 1)
    (= (city-interest paris) 1)
    (= (city-interest roma) 1)
    (= (city-interest berlin) 1)
    (= (city-interest lisboa) 1)
    (= (city-interest oporto) 2)
    (= (city-interest viena) 3)
    (= (city-interest praga) 3)

    (hotel-in hbarcelona barcelona)
    (hotel-in hparis paris)
    (hotel-in hroma roma)
    (hotel-in hberlin berlin)
    (hotel-in hlisboa lisboa)
    (hotel-in hoporto oporto)
    (hotel-in hviena viena)
    (hotel-in hpraga praga)

    (flight barcelona paris)
    (flight paris barcelona)
    (flight paris roma)
    (flight roma paris)
    (flight roma berlin)
    (flight berlin roma)
    (flight berlin lisboa)
    (flight lisboa berlin)
    (flight lisboa oporto)
    (flight oporto lisboa)
    (flight oporto viena)
    (flight viena oporto)
    (flight viena praga)
    (flight praga viena)
    (flight barcelona roma)
    (flight roma barcelona)
    (flight paris berlin)
    (flight berlin paris)
    (flight roma lisboa)
    (flight lisboa roma)
    (flight berlin oporto)
    (flight oporto berlin)
  )

  (:goal
    (trip-finished)
  )

  (:metric minimize (total-interest))
)
