(define (problem caso1-ext2-prefiere-ciudades-interes-bajo)
  (:domain viaje-extension2)

  (:objects
    barcelona paris roma berlin lisboa oporto viena praga - city
    hbarcelona hparis hroma hberlin hlisboa hoporto hviena hpraga - hotel
  )

  (:init
    (= (visited-count) 0)
    (= (min-cities) 4)
    (= (min-days-city) 1)
    (= (max-days-city) 2)
    (= (total-days) 0)
    (= (min-total-days) 4)
    (= (total-interest) 0)

    (= (days-in-city barcelona) 0)
    (= (days-in-city paris) 0)
    (= (days-in-city roma) 0)
    (= (days-in-city berlin) 0)
    (= (days-in-city lisboa) 0)
    (= (days-in-city oporto) 0)
    (= (days-in-city viena) 0)
    (= (days-in-city praga) 0)

    (= (city-interest barcelona) 1)
    (= (city-interest paris) 1)
    (= (city-interest roma) 1)
    (= (city-interest berlin) 1)
    (= (city-interest lisboa) 2)
    (= (city-interest oporto) 2)
    (= (city-interest viena) 3)
    (= (city-interest praga) 3)

    (hotel-in hbarcelona barcelona)
    (hotel-in hparis paris)
    (hotel-in hroma roma)
    (hotel-in hberlin berlin)
    (hotel-in hlisboa lisboa)
    (hotel-in hoporto oporto)
    (hotel-in hviena viena)
    (hotel-in hpraga praga)

    (flight barcelona paris)
    (flight paris barcelona)
    (flight barcelona roma)
    (flight roma barcelona)
    (flight barcelona berlin)
    (flight berlin barcelona)
    (flight paris roma)
    (flight roma paris)
    (flight paris berlin)
    (flight berlin paris)
    (flight roma berlin)
    (flight berlin roma)
    (flight lisboa oporto)
    (flight oporto lisboa)
    (flight viena praga)
    (flight praga viena)
    (flight barcelona lisboa)
    (flight lisboa barcelona)
    (flight paris oporto)
    (flight oporto paris)
    (flight roma viena)
    (flight viena roma)
    (flight berlin praga)
    (flight praga berlin)
  )

  (:goal
    (trip-finished)
  )

  (:metric minimize (total-interest))
)
